// <auto-generated />
using System;
using DistribuidoraLaVilla.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistribuidoraLaVilla.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260608180420_AddMetodoPagoToCajaMovimientos")]
    partial class AddMetodoPagoToCajaMovimientos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.AuditoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_auditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<string>("IdEntidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id_entidad");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.ToTable("auditoria");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Caja.CajaAperturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_apertura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("diferencia");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cierre");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_final");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_inicial");

                    b.Property<decimal?>("TotalEgresos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_egresos");

                    b.Property<decimal?>("TotalIngresos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_ingresos");

                    b.HasKey("Id");

                    b.ToTable("caja_apertura");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Caja.CajaMovimientoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("concepto");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdApertura")
                        .HasColumnType("int")
                        .HasColumnName("id_apertura");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int?>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.Property<int?>("IdRecibo")
                        .HasColumnType("int")
                        .HasColumnName("id_recibo");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("Id");

                    b.ToTable("caja_movimientos");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Caja.ReciboEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recibo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cliente_nombre");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_emision");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal?>("MontoPagado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_recibo");

                    b.HasKey("Id");

                    b.ToTable("recibos_caja");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.CategoriaMateriaPrimaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_materia_prima");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categorias_materia_prima");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.ClientesEntity", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("DiasCredito")
                        .HasColumnType("int")
                        .HasColumnName("dias_credito");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limite_credito");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.EstadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Facturacion.CuentasCobrarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cxc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.Property<decimal?>("SaldoPendiente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_pendiente");

                    b.HasKey("Id");

                    b.ToTable("cuentas_por_cobrar");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Facturacion.DetalleFacturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<bool?>("EsVentaPorPeso")
                        .HasColumnType("bit")
                        .HasColumnName("es_venta_por_peso");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int?>("IdLote")
                        .HasColumnType("int")
                        .HasColumnName("id_lote");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<decimal?>("PesoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("peso_total");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<decimal?>("PrecioKilo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_kilo");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.ToTable("detalle_factura");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Facturacion.EstadoFacturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("estados_factura");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Facturacion.FacturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int?>("FormaPago")
                        .HasColumnType("int")
                        .HasColumnName("forma_pago");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago");

                    b.Property<int?>("TipoFactura")
                        .HasColumnType("int")
                        .HasColumnName("tipo_factura");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Facturacion.PagoCuentaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago");

                    b.Property<int?>("IdCxc")
                        .HasColumnType("int")
                        .HasColumnName("id_cxc");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal?>("MontoPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_pago");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacion");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("referencia");

                    b.HasKey("Id");

                    b.ToTable("pagos_cuentas");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Facturacion.TipoFacturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipos_factura");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.LotesMateriaPrimaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_lote_materia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_disponible");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_inicial");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_total");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_unitario");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_entrada");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<Guid>("IdProveedor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.HasKey("Id");

                    b.ToTable("lotes_materia_prima");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.MarcasEntity", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.MateriaPrimaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_materia_prima");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("materia_prima");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.MovimientoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_movimiento");

                    b.Property<Guid?>("IdEntidad")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_entidad");

                    b.Property<int?>("IdLoteProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_lote_producto");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacion");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_movimiento");

                    b.Property<decimal>("TotalMovimiento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_movimiento");

                    b.HasKey("Id");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.MovimientosMateriaPrimaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdLoteMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_lote_materia");

                    b.Property<int>("IdTipoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_movimiento");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion");

                    b.HasKey("Id");

                    b.ToTable("movimientos_materia_prima");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Productos.CategoriasProductosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categorias_productos");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Productos.LotesProductosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_lote");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_disponible");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_inicial");

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_unidades");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_entrada");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<Guid>("IdProveedor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("peso_total");

                    b.Property<decimal>("PrecioKilo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_kilo");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_total");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("Id");

                    b.ToTable("lotes_productos");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Productos.MovimientosProductosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_movimiento");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdLoteProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_lote_producto");

                    b.Property<Guid?>("IdProveedor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_movimiento");

                    b.Property<decimal>("TotalMovimiento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_movimiento");

                    b.HasKey("Id");

                    b.ToTable("movimientos_productos");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Productos.OrdenProduccionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_orden");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadProducir")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_producir");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_completada");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_orden");

                    b.Property<int?>("IdLoteGenerado")
                        .HasColumnType("int")
                        .HasColumnName("id_lote_generado");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.ToTable("ordenes_produccion");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Productos.ProductosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioPorKilo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_por_kilo");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<bool>("VentaPorPeso")
                        .HasColumnType("bit")
                        .HasColumnName("venta_por_peso");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.Productos.RecetaProductoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_receta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRequerida")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad_requerida");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int>("IdMateriaPrima")
                        .HasColumnType("int")
                        .HasColumnName("id_materia_prima");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.HasKey("Id");

                    b.ToTable("recetas_producto");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.ProveedoresEntity", b =>
                {
                    b.Property<Guid>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<int?>("TipoProveedor")
                        .HasColumnType("int")
                        .HasColumnName("tipo_proveedor");

                    b.HasKey("IdProveedor");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.TipoMovimientoMateriaPrimaEntity", b =>
                {
                    b.Property<int>("IdTipoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMovimiento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoMovimiento");

                    b.ToTable("TiposMovimientoMateriaPrima");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.UnidadMedidaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("simbolo");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("unidad_medida");
                });

            modelBuilder.Entity("DistribuidoraLaVilla.Domain.Entities.UsuariosEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
